// Public form API. Serves any form definition and accepts its responses.
//
//   GET  /f/<slug>          -> schema with every answer key STRIPPED
//   POST /f/<slug>/upload   -> mint one signed upload URL for one file field
//   POST /f/<slug>          -> validate, score server-side, store
//
// Public by design: trainees scan a QR, they have no credentials. verify_jwt
// off for that reason. Writes go through the service-role key server-side; the
// browser never holds a key and the tables have RLS with no policies.
//
// Split into two modules on purpose: as one file the deploy payload was large
// enough to truncate. Same failure the ekip function has, same fix.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { Field, initUploads, issueUpload, spendUploads, takeFile } from "./upload.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
initUploads(SUPABASE_URL, SERVICE_KEY);

const ALLOWED = new Set([
  "https://konkret-haiti.com",
  "https://www.konkret-haiti.com",
]);

// A drawn signature arrives as a PNG data URL. Typically 4-20 KB; the cap is
// generous but finite so nobody can post a megabyte into a jsonb column.
const SIG_MAX = 400_000;
const TEXT_MAX = 4_000;

function cors(origin: string | null) {
  const h: Record<string, string> = {
    "Access-Control-Allow-Headers": "content-type",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Max-Age": "86400",
    "Vary": "Origin",
  };
  if (origin && ALLOWED.has(origin)) h["Access-Control-Allow-Origin"] = origin;
  return h;
}

function slugOf(url: string): string {
  const parts = new URL(url).pathname.split("/").filter(Boolean);
  const i = parts.lastIndexOf("f");
  const rest = i >= 0 ? parts.slice(i + 1) : parts;
  if (rest.length) return rest[0];
  return new URL(url).searchParams.get("s") ?? "";
}

// /f/<slug>/upload -> "upload"
function subOf(url: string): string {
  const parts = new URL(url).pathname.split("/").filter(Boolean);
  const i = parts.lastIndexOf("f");
  const rest = i >= 0 ? parts.slice(i + 1) : parts;
  return rest.length > 1 ? rest[1] : "";
}

// THE important function. Anything returned to a browser goes through here.
// If an answer key ever leaks, the gate is decorative.
function strip(schema: Record<string, unknown>) {
  const out = JSON.parse(JSON.stringify(schema));
  for (const sec of out.sections ?? []) {
    for (const f of sec.fields ?? []) delete f.answer;
  }
  return out;
}

function fieldsOf(schema: Record<string, unknown>): Field[] {
  const out: Field[] = [];
  for (const sec of (schema.sections ?? []) as Record<string, unknown>[]) {
    for (const f of (sec.fields ?? []) as Field[]) out.push(f);
  }
  return out;
}

function setEq(got: unknown, want: unknown[]) {
  const g = new Set(Array.isArray(got) ? got.map(String) : []);
  return g.size === want.length && want.every((v) => g.has(String(v)));
}

// Success messages may carry {referans}; the reference is generated by a
// database trigger on insert, so it can only be filled in afterwards.
function fill(msg: string, referans: string | null) {
  return msg.replace(/\{referans\}/g, referans ?? "");
}

const sb = () => createClient(SUPABASE_URL, SERVICE_KEY);

Deno.serve(async (req: Request) => {
  const ch = cors(req.headers.get("origin"));
  const json = { ...ch, "Content-Type": "application/json; charset=utf-8" };
  const bad = (msg: string, status = 400) =>
    new Response(JSON.stringify({ error: msg }), { status, headers: json });

  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: ch });

  const slug = slugOf(req.url);
  if (!slug) return bad("Ki fòm?", 400);
  const sub = subOf(req.url);

  const { data: fom, error } = await sb()
    .from("ekip_fom").select("id,slug,tit,deskripsyon,schema,eta")
    .eq("slug", slug).maybeSingle();

  if (error) { console.error("lookup failed", error); return bad("Gen yon pwoblèm teknik.", 500); }
  if (!fom) return bad(`Fòm "${slug}" pa egziste.`, 404);

  // ------------------------------------------------------------- GET
  if (req.method === "GET") {
    return new Response(JSON.stringify({
      slug: fom.slug, tit: fom.tit, deskripsyon: fom.deskripsyon,
      eta: fom.eta, schema: strip(fom.schema),
    }), { headers: json });
  }

  if (req.method !== "POST") return bad("Method not allowed", 405);

  // ------------------------------------------------------------ POST
  if (fom.eta !== "live") {
    return bad(fom.eta === "bouyon" ? "Fòm sa a poko louvri." : "Fòm sa a fèmen.", 409);
  }

  const fields = fieldsOf(fom.schema);

  // After the live gate on purpose: no uploads into a draft or closed form, so
  // a stale QR cannot be used as free storage.
  if (sub === "upload") {
    const r = await issueUpload(req, fom, fields);
    return new Response(JSON.stringify(r.body), { status: r.status, headers: json });
  }

  let body: Record<string, unknown>;
  try { body = await req.json(); } catch { return bad("bad json"); }

  if (typeof body.website === "string" && body.website.trim()) {
    return new Response(JSON.stringify({ ok: true, msg: "Mèsi." }), { headers: json });
  }

  const repons: Record<string, unknown> = {};
  const manke: string[] = [];
  const attach: string[] = [];

  for (const f of fields) {
    let v = body[f.key];

    if (f.type === "checkbox") {
      v = Array.isArray(v) ? v.map(String) : [];
    } else if (f.type === "number" || f.type === "currency" || f.type === "rating") {
      v = v === "" || v == null ? null : Number(v);
      if (v !== null && Number.isNaN(v)) v = null;
    } else if (f.type === "signature") {
      const s = v == null ? "" : String(v);
      if (s && !/^data:image\/(png|jpeg);base64,/.test(s)) {
        return bad(`Siyati "${f.label ?? f.key}" pa bon.`);
      }
      if (s.length > SIG_MAX) return bad(`Siyati "${f.label ?? f.key}" twò gwo.`);
      v = s;
    } else if (f.type === "file") {
      const r = await takeFile(v, fom, f);
      if (!r.ok) return bad(r.msg, r.status);
      v = r.val;
      if (r.path) attach.push(r.path);
    } else {
      v = v == null ? "" : String(v).trim().slice(0, TEXT_MAX);
    }

    const empty = f.type === "checkbox"
      ? (v as string[]).length === 0
      : (v === "" || v === null);
    if (f.required && empty) manke.push(f.label || f.key);
    repons[f.key] = v;
  }

  if (manke.length) return bad("Chan sa yo obligatwa: " + manke.join(", "));

  // scoring, only if the form declares a pass mark
  const passMark = (fom.schema as Record<string, unknown>).pass_mark;
  let esko: number | null = null;
  let total: number | null = null;
  let pase: boolean | null = null;

  const scored = fields.filter((f) => f.answer !== undefined);
  if (typeof passMark === "number" && scored.length) {
    esko = 0;
    total = scored.length;
    for (const f of scored) {
      const got = repons[f.key];
      const ok = Array.isArray(f.answer)
        ? setEq(got, f.answer as unknown[])
        : String(got) === String(f.answer);
      if (ok) esko++;
    }
    pase = esko >= passMark;
  }

  // select() back for the id (to spend uploads) and the reference the trigger
  // generated (to show the person)
  const { data: saved, error: insErr } = await sb().from("ekip_repons").insert({
    fom_id: fom.id, fom_slug: fom.slug, repons, esko, total, pase,
    meta: { ua: (req.headers.get("user-agent") ?? "").slice(0, 300) },
  }).select("id,referans").maybeSingle();

  if (insErr) {
    console.error("insert failed", insErr);
    return bad("Gen yon pwoblèm teknik. Tanpri eseye ankò.", 500);
  }

  // Spend the uploads only now. Had the insert failed, the paths stay
  // redeemable and the queued retry works instead of losing the photo.
  if (saved?.id) await spendUploads(attach, saved.id);

  const referans = saved?.referans ?? null;
  const sch = fom.schema as Record<string, string>;
  const raw = pase === null
    ? (sch.success_message ?? "Mèsi. Repons ou anrejistre.")
    : pase ? (sch.pass_message ?? "Ou pase.") : (sch.fail_message ?? "Ou pa pase fwa sa a.");

  return new Response(JSON.stringify({
    ok: true, esko, total, pase, referans, msg: fill(raw, referans),
  }), { headers: json });
});
